server:
  port: 7002

#logging:
logging:
  level:
    root: info
    com.ftrako: debug
  config: classpath:log4j2.yml

eureka:
  #  instance:
  #  appname: orderapisrv
  client:
    register-with-eureka: true # 表示注册
    fetch-registry: true # 从注册中心获取其他服务的地址
    service-url:
      defaultZone: http://localhost:7000/eureka,http://localhost:6001/eureka # 不搭建集群，单机，指向自己

spring:
  application:
    name: orderapisrv
feign:
  circuitbreaker:
    enabled: true

